title: 友情链接
subtitle: 优秀的博主和朋友们

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: friends

categories:
  - name: 技术博主
    icon: fas fa-user-friends
    sites:
      - name: 阿虚同学的储物间
        url: https://axutongxue.cn
        icon: fas fa-sitemap
        description: 实用导航
      - name: 奔跑中的奶酪
        url: https://www.runningcheese.com
        icon: far fa-chess-queen
        description: 技术分享
      
  - name: 技术社区
    icon: fas fa-laptop-code
    sites:
      - name: GitHub
        icon: fab fa-github
        description: 开源代码托管平台
        url: https://github.com
      - name: IT天空
        url: https://www.itsk.com
        icon: fab fa-skyatlas
        description: 以系统封装技术与驱动技术为主的综合性IT站点
      - name: Stack Overflow
        icon: fab fa-stack-overflow
        description: 程序员问答社区
        url: https://stackoverflow.com 