title: 
subtitle: 个人导航站点

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: home

categories:
  - name: 常用网站
    icon: fas fa-star
    sites:
      - name: 金山文档
        url: https://www.kdocs.cn
        icon: fab fa-dochub
        description: 可多人实时协作编辑的在线文档
      - name: 河南地矿职业学院
        url: http://www.hagmc.edu.cn
        icon: fas fa-school
        description: 河南地矿职业学院官网
      - name: 阿里云中学堂
        url: https://college.aliyun.com
        icon: fas fa-cloud
        description: 阿里云培训中心面向客户提供的集“学-练-测-证”于一体的一站式在线学习与实践平台
      - name: 超星学习通
        url: https://passport2.chaoxing.com
        icon: fas fa-book
        description: 超星学习通登录
      - name: 今日热榜
        url: https://tophub.today/c/news
        icon: fas fa-magnifying-glass
        description: 新闻热搜榜
      - name: 阿虚同学的储物间
        url: https://axutongxue.cn
        icon: fas fa-sitemap
        description: 实用导航
      - name: IT天空
        url: https://www.itsk.com
        icon: fab fa-skyatlas
        description: 以系统封装技术与驱动技术为主的综合性IT站点  
      - name: my导航
        url: https://yanglf.ysepan.com
        icon: fas fa-sitemap
        description: 网站软件收藏
      - name: 个人博客
        url: https://ylfei-github-io.pages.dev
        icon: fas fa-blog
        description: 个人博客
      - name: 蛙蛙工具
        url: https://www.iamwawa.cn
        icon: fas fa-toolbox
        description: 便捷的在线工具网站
  - name: 电子邮箱
    icon: fas fa-envelopes-bulk
    sites:
      - name: 126邮箱
        url: https://mail.126.com
        icon: fas fa-envelope
        description: 网易126免费邮箱--你的专业电子邮局
      - name: 163邮箱
        url: https://mail.163.com
        icon: fas fa-envelope
        description: 网易163免费邮箱--中文邮箱第一品牌
      - name: QQ邮箱
        url: https://mail.qq.com
        icon: fas fa-envelope
        description: QQ邮箱,常联系！
      - name: 腾讯企业邮箱
        url: https://exmail.qq.com/login
        icon: fas fa-envelope-open-text
        description: 腾讯企业邮箱，唯一可以在微信中收发邮件的企业邮箱
      - name: 临时邮箱
        url: https://24mail.chacuo.net
        icon: fas fa-envelope
        description: 临时邮箱、24小时邮箱      
  - name: 学习资源
    icon: fas fa-graduation-cap
    sites:
      - name: 哔哩哔哩
        url: https://www.bilibili.com
        icon: fas fa-play-circle
        description: 视频学习平台
      - name: 中国大学MOOC（慕课）
        url: https://www.icourse163.org
        icon: fas fa-book
        description: 中国大学MOOC（慕课）国家精品课程在线学习平台
      - name: 超星学习通
        url: https://passport2.chaoxing.com
        icon: fas fa-book
        description: 超星学习通登录
      - name: LeetCode
        url: https://leetcode.cn
        icon: fas fa-code
        description: 算法刷题平台
  - name: 软件工具
    icon: fas fa-tools
    sites:
      - name: MSDN
        url: https://msdn.itellyou.cn
        icon: fab fa-windows
        description: MSDN,我告诉你
      - name: Office Tool Plus
        url: https://otp.landian.vip/zh-cn
        icon: fab fa-microsoft
        description: 基于Office部署工具制作，除此之外还集成了各种实用性工具
      - name: 果核剥壳
        url: https://www.ghxi.com
        icon: fab fa-docker
        description: 博客类型的资源分享软件，分享绿色软件软件等
      - name: 枫音应用
        url: https://fy6b.com
        icon: fab fa-docker
        description: 专注分享免费、绿色实用软件
      - name: 正版中国
        url: https://www.getitfree.cn
        icon: fab fa-docker
        description: 以提供正版软件限时免费信息为途径,引导用户养成使用正版软件的习惯
      - name: 腾讯软件中心
        url: https://pc.qq.com
        icon: fab fa-docker
        description: 提拱海量免费软件安全下载  
      - name: 奔跑中的奶酪
        url: https://www.runningcheese.com
        icon: fab fa-docker
        description: 技术分享
      - name: 小鱼儿yr系统
        url: https://www.yrxitong.com
        icon: fab fa-docker
        description: 专注于系统封装重装系统下载软件分享教程
      - name: VS Code
        url: https://code.visualstudio.com
        icon: fas fa-code
        description: 强大的代码编辑器
      - name: Git
        url: https://git-scm.com
        icon: fab fa-git-alt
        description: 版本控制工具
      - name: QuickLook
        url: https://github.com/QL-Win/QuickLook
        icon: fas fa-users-viewfinder
        description: QuickLook
  - name: 设计资源
    icon: fas fa-palette
    sites:
      - name: SDC优设网配色工具
        url: https://color.uisdc.com
        icon: fab fa-figma
        description: 优设网帮助您完成配色方案，不用配色软件轻松配色
      - name: HTML拾色器
        url: https://www.runoob.com/tags/html-colorpicker.html
        icon: fab fa-dribbble
        description: HTML拾色器
      - name: 中国传统颜色
        url: https://zhongguose.com
        icon: fab fa-behance
        description: 中国传统颜色
      - name: IconFont
        url: https://www.iconfont.cn
        icon: fas fa-icons
        description: 图标资源库
  - name: 在线工具
    icon: fas fa-wrench
    sites:
      - name: JSON Editor
        url: https://jsoneditoronline.org
        icon: fas fa-code-branch
        description: JSON在线编辑器
      - name: Can I Use
        url: https://caniuse.com
        icon: fas fa-browser
        description: 浏览器兼容性查询
      - name: TinyPNG
        url: https://tinypng.com
        icon: fas fa-compress
        description: 图片压缩工具
      - name: Carbon
        url: https://carbon.now.sh
        icon: fas fa-code
        description: 代码图片生成器