title: 我的导航
description: 个人网络导航站
author: ylf
favicon: favicon.ico
logo_text: 导航站


fonts:
  title:
    family: Poppins
    weight: 700
    source: system
  subtitle:
    family: Quicksand
    weight: 500
    source: system
  body:
    family: Noto Sans SC
    weight: 400
    source: system
    
profile:
  title: "Hello"
  subtitle: "收集实用网站和工具"
  description: 

social:
  - name: GitHub
    url: https://github.com/ylfei/z
    icon: fab fa-github
  - name: 旧版导航
    url: https://ylfei.github.io/d
    icon: fab fa-github 
  - name: 今日热榜
    url: https://tophub.today/c/news
    icon: fas fa-magnifying-glass
    description: 新闻热搜榜
