title: 我的导航
description: 个人网络导航站
author: ylfei
favicon: favicon.ico
logo_text: 导航站

theme:
  default: "light"
  toggleIcon: true

fonts:
  title:
    family: Poppins
    weight: 400
    source: system
  subtitle:
    family: Quicksand
    weight: 400
    source: system
  body:
    family: Noto Sans SC
    weight: 300
    source: system
    
profile:
  title: 
  subtitle: "收集实用网站和工具"
  description: 

social:
  - name: GitHub
    url: https://github.com
    icon: fab fa-github
  - name: Telegram
    url: https://t.me
    icon: fab fa-telegram
  